### ISSUE TITLE
CRASH WHEN SET PROFILE PICTURE AFTER ENABLE MODE 

### ISSUE THREAD

**Issue by muhammadarif1** [amit-bhandari/AB-Remote-Wallpaper-Changer#2]
#### PROJECT INFO
 REPOSITORIES : https://github.com/amit-bhandari/AB-Remote-Wallpaper-Changer
APP NAME           :AB Remote Wallpaper Changer -HD Photos for Friends
LINK DOWNLOAD :https://play.google.com/store/apps/details?id=in.thetechguru.walle.remote.abremotewallpaperchanger

#### EXPECTED BEHAVIOR
  when the user wants to change his profile photo should the user be able to set it up there is no problem after the user set the rotation and flip the image

#### ACTUAL BEHAVIOR
  when users want to change their account profile picture then the user set the rotation and flip the image then the user press ```crop ``` button this app instead crashes and takes the user back to the front page of the application

#### how to reproduce 
- download AB Remote Wallpaper Changer -HD Photos for Friends from playstore 
- launch the app and then sing in whit your account 
- swipe to the right side to account ```profile``` option 
-enable block mode and then disable again 
- click on account logo 
-  pick picture from galery 
- click on the 3 dots at the rigt side and click rotate 
- after that click on 3 dots against and chose flip option and then chose flip ```flip horizontal``` feature and click crop option and note the bug

app version : ab remote walpaper v 1.0.0
device info   : android 5.1 idos

#### BUG RECORDING 
https://youtu.be/DbO2MdUI590

#### LOGCAT FILE 
```FATAL EXCEPTION: main
Process: in.thetechguru.walle.remote.abremotewallpaperchanger, PID: 9437
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=203, result=-1, data=Intent { (has extras) }} to activity {in.thetechguru.walle.remote.abremotewallpaperchanger/in.thetechguru.walle.remote.abremotewallpaperchanger.activity_fragments.ActivityMain}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ProgressBar.setVisibility(int)' on a null object reference
    at android.app.ActivityThread.deliverResults(ActivityThread.java:3665)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:3708)
    at android.app.ActivityThread.access$1300(ActivityThread.java:157)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5376)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:947)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ProgressBar.setVisibility(int)' on a null object reference
    at in.thetechguru.walle.remote.abremotewallpaperchanger.activity_fragments.FragmentProfile.uploadPhoto(FragmentProfile.java:100)
    at in.thetechguru.walle.remote.abremotewallpaperchanger.activity_fragments.FragmentProfile.onActivityResult(FragmentProfile.java:82)
    at in.thetechguru.walle.remote.abremotewallpaperchanger.activity_fragments.ActivityMain.onActivityResult(ActivityMain.java:97)
    at android.app.Activity.dispatchActivityResult(Activity.java:6226)
    at android.app.ActivityThread.deliverResults(ActivityThread.java:3661)```

**Comment by amit-bhandari** [comment]
Thanks for the bug report. I am able to reproduce this. Will check soon

**Comment by amit-bhandari** [comment]
Solved in latest beta release. Will close it once goes in productionnk
